---
- name: Deploy Kubernetes Deployment and Check Pod Status
  hosts: localhost
  tasks:
    - name: Apply the deployment
      command: kubectl apply -f hello-world-deployment.yml 
      register: apply_result

    - name: Wait for the pod to be in running state
      command: kubectl get pods -l app=hello-world -o jsonpath='{.items[0].status.phase}'
      register: pod_status
      until: pod_status.stdout == "Running"
      retries: 10
      delay: 5

