---
- name: Deploy Kubernetes Secret, Ingress, and Check Ingress Status
  hosts: localhost
  tasks:
    - name: Apply the Secret
      command: kubectl apply -f hello-world-secret.yml
      register: apply_secret_result

    - name: Check if the Secret was created successfully
      command: kubectl get secret hello-world-secret -o jsonpath='{.metadata.name}'
      register: secret_check
      until: secret_check.stdout == "hello-world-secret"
      retries: 5
      delay: 5

    - name: Apply the Ingress
      command: kubectl apply -f hello-world-ingress.yml
      register: apply_ingress_result
      when: secret_check.stdout == "hello-world-secret"

    - name: Wait for the Ingress to have an assigned IP
      command: kubectl get ingress hello-world-ingress -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: ingress_ip
      until: ingress_ip.stdout != ""
      retries: 10
      delay: 5

