---
- name: Deploy Kubernetes Deployment, Service, and Ingress, and Check Pod and Ingress Status
  hosts: localhost
  tasks:
    - name: Apply the ingress
      command: kubectl apply -f hello-world-ingress.yml
      register: apply_ingress_result

    - name: Wait for the ingress to have an assigned IP
      command: kubectl get ingress  -o jsonpath='{.items[0].status.loadBalancer.ingress[0].ip}'
      register: ingress_ip
      until: ingress_ip.stdout != ""
      retries: 10
      delay: 5
